name: Deploy Static Site to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: tester-g3cng5akbsb4h2hc.ukwest-01
          slot-name: production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
